### ISSUE TITLE
Unable to add libraries using pip

### ISSUE THREAD

**Issue by 5AbhishekSaxena** [pemagrg1/text_summarization#1]
I tried to use this project but couldn't successfully execute the pip commands to install pyteaser and pytldr libraries due to beautifulsoap4 error.

Detailed explanation on the issue : https://stackoverflow.com/questions/59685464/unable-to-install-libraries-with-pip-due-to-outdated-beautifulsoup

**Comment by pemagrg1** [comment]
pyteaser and pytldr libraries doens't work in python>2.7 since the code format doesn't meet the requirements for python3. <br>
In python2.7,  you can install **pyteaser** using:<br> `pip install git+https://github.com/xiaoxu193/PyTeaser.git` <br> or `pip install pyteaser` didn't work.<br>
Similarly for pytldr: <br>
pip install git+https://github.com/jaijuneja/PyTLDR.git
<br> or `pip install pytldr` didn't work.<br>
